# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ias-web-app

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://iasprojectacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_24eda8e8831448bf8eb0cd1371b7cf37 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_487a754d1a5f4e57b095c43a4fe23743 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: iasprojectacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_24eda8e8831448bf8eb0cd1371b7cf37 }}/ias-project:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ias-web-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f59d2230aabe4ace88051d8db47bcb31 }}
        images: 'iasprojectacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_24eda8e8831448bf8eb0cd1371b7cf37 }}/ias-project:${{ github.sha }}'