# This is a basic workflow to help you get started with Actions

name: remote ssh command

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - id: 'compute-ssh'
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: 'lifeanalytics-vm'
          zone: 'us-central1-f'
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          command: cd ias-project-react && git pull https://oauth2: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@github.com/daisukekubota0823/ias-project-react.git 
                    # git reset --hard && 
                    # export NVM_DIR=~/.nvm && source ~/.nvm/nvm.sh &&
                    # npm -v && cd react && npm i && npm run build && 
                    # rm -R /var/www/html-IAS/* && cp ./build/* /var/www/html-IAS/ && cd .. && docker-compose up -d
